version: '2.2'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
       - ./data:/usr/share/elasticsearch/data
    networks:
      - graylog

  mongodb:
    image: mongo:4
    container_name: mongodb
    networks:
      - graylog
    mem_limit: 1g
    volumes:
     - ./mongo_data:/data/db

  graylog:
    image: graylog/graylog:4.3.8
    container_name: graylog
    volumes:
      - ./journal:/usr/share/graylog/data/journal
      #- ./node-id:/usr/share/graylog/data/config/node-id
    env_file:
      - .env
    environment:
      - GRAYLOG_PASSWORD_SECRET=${secret}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${admin_password}
      - GRAYLOG_HTTP_EXTERNAL_URI=${uri}
      - GRAYLOG_ELASTICSEARCH_HOSTS=${es_host}
      - GRAYLOG_MONGODB_URI=${mongo_uri}
      - GRAYLOG_ROOT_TIMEZONE=${timezone}
      - GRAYLOG_SERVER_JAVA_OPTS=-Xms1g -Xmx1g -XX:NewRatio=1 -server -XX:+ResizeTLAB -XX:+UseConcMarkSweepGC -XX:+CMSConcurrentMTEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:-OmitStackTraceInFastThrow
      - GRAYLOG_PROMETHEUS_EXPORTER_ENABLED=true
      - GRAYLOG_PROMETHEUS_EXPORTER_BIND_ADDRESS=0.0.0.0:9833
    networks:
      - graylog
    mem_limit: 2g
    ports:
      # Graylog web GUI
      - 9000:9000
      # Prometheus exporter
      - 9833:9833
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

networks:
  graylog:
    driver: bridge
